### ISSUE TITLE
[BUG]: Unable to Import Component from Canvas Component Library from Creator Kit (App Source Installation)

### ISSUE THREAD

**Issue by Dhruvinshah16** [microsoft/powercat-creator-kit#260]
**Describe the bug**
I imported Creator Kit Component Kit using App Source. I'm having below 3 solutions installed.
![image](https://user-images.githubusercontent.com/41663430/211129153-4e481a7c-2fcc-4600-86fc-5871b07e77df.png)

It installed Canvas Component Library and look like this.The owner is my account. So, No Permission Issues.

![image](https://user-images.githubusercontent.com/41663430/211129167-9aa75be9-6e0a-4078-a288-698a621e3d85.png)

When I created Canvas App and try to Import the components, it is not showing anything!
![image](https://user-images.githubusercontent.com/41663430/211129178-fc8a709f-3dd3-4ea6-8ea6-ef26d2ab9b46.png)

Earlier it was working properly. I think before 20th December everything was fine. Suddenly this is happening! This is only for Canvas Component.

Please help to resolve this!

**Comment by denisem-msft** [comment]
Thanks for flagging this @Dhruvinshah16, we are investigating and will update this thread

**Comment by tayb6883** [comment]
Following.
Working fine, in the base environment
whereas, while importing managed solution of the canvas to prod.
The creator kit is already imported into the environment, whereas creator components are not being picked properly in the canvas

**Comment by briangre** [comment]
same issue here when installing from AppSource... the installation goes well, but the components from the component library are not available to be used.

**Comment by Dhruvinshah16** [comment]
The issue is when importing from App Source and Updating from App Source!

**Comment by denisem-msft** [comment]
Thanks to everyone who posted and sorry for the inconvenience. If you can, please help us by sharing more details (e.g., session ID of the studio session where components were inaccessible) here to help us investigate further: https://forms.microsoft.com/r/XErgLKUZrY

**Comment by Dhruvinshah16** [comment]
Any updates on this Bug? Many people are messaging and adding comments for the same video I created 1.5 months back!
Is this issue resolved?

**Comment by denisem-msft** [comment]
We had an issue with the build pipeline and are working on re-deploying the solution. Thank you for your patience.

**Comment by denisem-msft** [comment]
Please download the CreatorKitCore solution from the latest release page, the component library should be working: https://github.com/microsoft/powercat-creator-kit/releases/tag/CreatorKit-November2022

Direct download link: https://github.com/microsoft/powercat-creator-kit/releases/download/CreatorKit-November2022/CreatorKitCore_1.0.20230118.1_managed.zip

**Comment by Dhruvinshah16** [comment]
Does that mean I manually need to update the solution? Will that not work with the update of the already installed package from App Souce?

**Comment by denisem-msft** [comment]
Please manually update the solution for now. We will update the AppSource offering as soon as possible and update this thread when complete.

**Comment by SIKYAN** [comment]
I have maunally uploaded the latest version of solutions package, but still the same issue!

![image](https://user-images.githubusercontent.com/66454128/219318136-e6177af3-9eb7-4e17-9d1a-741f41f32468.png)

**Comment by denisem-msft** [comment]
@SIKYAN can you please confirm if you have enabled code components in the environment you're working in? https://learn.microsoft.com/en-us/power-apps/developer/component-framework/component-framework-for-canvas-apps#enable-the-power-apps-component-framework-feature

**Comment by SIKYAN** [comment]
I'm pretty sure that's enabled!
![image](https://user-images.githubusercontent.com/66454128/219517051-ed69619c-2eb1-4822-8e4b-700ca9e1f5c3.png)

**Comment by rsaulat** [comment]
The issue is not fixed yet as of 1st May 2023.
