### ISSUE TITLE
[BUG]: Fluent detail list not showing items

### ISSUE THREAD

**Issue by MarcosSalasIni** [microsoft/powercat-creator-kit#406]
**Describe the bug**
I have a solution with several Dataverse tables and a Power Apps
I'm using some Fluent detail list and i know how this works, in fact i'm using several of them in the app.
The problem is that isntead of displaying the items it displays only some grey rows without information. When refreshing the data source, all rows display by a moment and then they dissapear again.
But the information is well selected, in the fx panel the items can be watched

**To Reproduce**
Steps to reproduce the behavior (i 'm not completely sure but i think that this may trigger the bug):
![panel x](https://github.com/microsoft/powercat-creator-kit/assets/145750617/adccc980-190a-4089-a41d-f525c3e8298f)

1. Have a soultion with dataverse tables
2. Configure a detail list and make it work!
3. Trying to delete the Dataverse table from the app (i couldn't do this, when i deleted it, the datasource automatically reassings to the projejct) i think that this fact triggers the bug

**Expected behavior**
A working detail list

**Comment by MarcosSalasIni** [comment]
Thank you, i'm gonna try it!

**Comment by MarcosSalasIni** [comment]
> Has something to do with the Authoring version of Power Apps. With version 3.23084.14 details list is working but the version is almost out of the list to be able to select so hopefully Microsoft or an update of the detaillist component is available.

I've updated to the latest version, but the problem keeps going

**Comment by mikkert** [comment]
Ok maybe I said it wrong the latest version where it is still working is with 3.23084.14. Every newer version the detailslist is bugged and not showing data.

**Comment by MarcosSalasIni** [comment]
Ok! that works but when i save the app and i reopened the version automatically changed to the original
And another question: Why is the detail list not showing items when in my app i have several of them, the rest are working correctly

**Comment by PowerThomas** [comment]
I'm having the same issue!

**Comment by kphillpotts** [comment]
As menioned by @mikkert I can also confirm that I am seeing a "loading style placeholder" instead of the data when using Authoring Version of Power Apps on or after 3.23091.14.  

I can switch between the older and the newer and see it fail without any other changes to my app.

<img width="460" alt="image" src="https://github.com/microsoft/powercat-creator-kit/assets/1327346/0fdf407a-06da-48b1-b7b8-a2007f25dc9f">

**Comment by MarcosSalasIni** [comment]
> As menioned by @mikkert I can also confirm that I am seeing a "loading style placeholder" instead of the data when using Authoring Version of Power Apps on or after 3.23091.14.
> 
> I can switch between the older and the newer and see it fail without any other changes to my app.
> 
> <img alt="image" width="460" src="https://user-images.githubusercontent.com/1327346/270129329-0fdf407a-06da-48b1-b7b8-a2007f25dc9f.png">

Hi!
That's perfect but only for a limited time. I change to the working authoring version and save the app.
But later the app automatically updates to the latest version, so it finally doesn't work 
How can i stop auto upgraping the app?

**Comment by walcivar** [comment]
Same here, yesterday I tried to change the authoring version, save and reload the app, but when I went to test the custom page from the Model Driven App, it takes the latest version. So indeed updating the authoring version doesn't work.

**Comment by MarcosSalasIni** [comment]
Is there any other fix for this issue?
In my app is critical

**Comment by MarcosSalasIni** [comment]
![limitation](https://github.com/microsoft/powercat-creator-kit/assets/145750617/24d9104c-53e3-4eb7-a213-a1713b1193b2)
So, There is no way to permanently change the authoring version.
Any idea to avoid rebuilding the app? Something that we could try or.. anything?

**Comment by MarcosSalasIni** [comment]
I fix it! if you use in the Items of the list SHowColumns it works

**Comment by kphillpotts** [comment]
> I fix it! if you use in the Items of the list SHowColumns it works

Hey @marcossalasini I'm not sure I understand, can you explain further?

**Comment by walcivar** [comment]
Thank you so much @MarcosSalasIni I've also added the ShowColumns in the Items property and now it's working. 

However, this should not be the default behaviour of the component. I hope Microsoft will make an adjustment as it was not necessary to add ShowColumns before. For now it works but at the cost of making the formula more complex.

@kphillpotts You can follow as an example in the image, the red square is what I have added in the Items property:

![image](https://github.com/microsoft/powercat-creator-kit/assets/5630463/285071d6-4383-48b5-af73-d5264d1c0e87)

**Comment by MarcosSalasIni** [comment]
![image](https://github.com/microsoft/powercat-creator-kit/assets/145750617/760304be-1915-45c0-9304-9dcc1409fe24)
It fixed in this way

**Comment by Lulli** [comment]
No this is not a really fix because now you have lost the ability to sort by column and you are not passing the sort filter to the dataverse table.

**Comment by MarcosSalasIni** [comment]
I know but if the component is bugged.... having an alternative is the best that we can have. That or rebuilding the whole app, at least in my case

**Comment by PStapperMazars** [comment]
Hello all, I have created a workaround on this issue. When I create an item for my Dataverse table, I created an #autonumber text field for that row. Now I am able to use that Unique code and subtract that record from my Dataverse table. 

It seems to be working.

**Comment by craigyh** [comment]
Hi All,
I still have this issue over 6 months later, has it still not been fixed?

Thanks Craig

**Comment by robmcalister** [comment]
It isn't fixed in the latest or recommended authoring versions with the newest version of the component library. Not sure what's going on with it.
